/**
 * Offline bilingual gazetteer search.
 *
 * The dataset lives in `data/gazetteer.json` (generated by
 * `scripts/build-gazetteer.mjs`) and is dynamically imported so it lands in its
 * own lazy chunk and never touches the first paint.
 */

/** Compressed record shape as stored on disk. */
interface RawPlace {
  z: string; // Chinese name (may be empty)
  n: string; // English name
  cz: string; // country name in Chinese (may be empty)
  c: string; // ISO-2 country code
  lat: number;
  lng: number;
  p: number; // population in thousands, for ranking
}

export interface Place {
  name: string; // preferred display name (Chinese if present, else English)
  nameZh: string;
  nameEn: string;
  country: string; // Chinese country name, falls back to ISO-2 code
  countryCode: string;
  lat: number;
  lng: number;
  population: number;
}

let cache: Promise<Place[]> | null = null;

/** Lowercase, trim, and strip combining diacritics for lenient matching. */
export function normalize(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');
}

/** Lazy-load and hydrate the gazetteer. Cached after the first call. */
export function loadGazetteer(): Promise<Place[]> {
  if (!cache) {
    cache = import('./data/gazetteer.json').then((module) => {
      const raw = (module.default ?? module) as unknown as RawPlace[];
      return raw.map((item) => ({
        name: item.z || item.n,
        nameZh: item.z,
        nameEn: item.n,
        country: item.cz || item.c,
        countryCode: item.c,
        lat: item.lat,
        lng: item.lng,
        population: item.p
      }));
    });
  }
  return cache;
}

/**
 * Rank places against a query. Chinese and English fields share the same
 * normalize path so casing / diacritics behave consistently.
 */
export function matchPlaces(places: Place[], query: string, limit = 8): Place[] {
  const q = normalize(query);
  if (!q) return [];

  const scored: { place: Place; score: number }[] = [];

  for (const place of places) {
    const zh = normalize(place.nameZh);
    const en = normalize(place.nameEn);
    const countryZh = normalize(place.country);
    const countryEn = normalize(place.countryCode);

    let score = -1;
    if (zh.startsWith(q) || en.startsWith(q)) {
      score = 3;
    } else if (zh.includes(q) || en.includes(q)) {
      score = 2;
    } else if (countryZh.includes(q) || countryEn.includes(q)) {
      score = 1;
    }

    if (score >= 0) scored.push({ place, score });
  }

  scored.sort((a, b) => b.score - a.score || b.place.population - a.place.population);
  return scored.slice(0, limit).map((entry) => entry.place);
}

/**
 * Search places by Chinese name, English name, or country name.
 * Prefix matches rank first, then higher population.
 */
export async function searchPlaces(query: string, limit = 8): Promise<Place[]> {
  const places = await loadGazetteer();
  return matchPlaces(places, query, limit);
}
